-- Platform seed (task 1.6): business parameter defaults and the system roles and permissions.
-- Parameters: every DB-located row of each module's requirements.md §4. Bounds are left NULL until
-- the leader sets them; see the platform Phase 1 PR. Roles and permissions: specs/auth/design.md §1.2,
-- seeding only the cells whose CASL condition the spec states exactly.
-- Generated from one data table; 48 parameters, 4 roles, 70 permissions, 82 grants.

INSERT INTO "business_parameters" ("key", "value", "valueType", "bounds", "unit", "ownerModule", "description", "version", "updatedAt") VALUES
  ('auth.passwordMinLength', '8'::jsonb, 'INT', NULL, 'characters', 'auth', 'Minimum password length', 1, CURRENT_TIMESTAMP),
  ('auth.loginMaxFailures', '5'::jsonb, 'INT', NULL, 'attempts', 'auth', 'Failed logins inside the failure window that lock the account', 1, CURRENT_TIMESTAMP),
  ('auth.loginFailureWindowMinutes', '15'::jsonb, 'INT', NULL, 'minutes', 'auth', 'Window in which failed logins are counted', 1, CURRENT_TIMESTAMP),
  ('auth.lockoutMinutes', '15'::jsonb, 'INT', NULL, 'minutes', 'auth', 'How long a locked account stays locked', 1, CURRENT_TIMESTAMP),
  ('auth.otpTtlMinutes', '10'::jsonb, 'INT', NULL, 'minutes', 'auth', 'Lifetime of an email one-time code', 1, CURRENT_TIMESTAMP),
  ('auth.otpMaxAttempts', '5'::jsonb, 'INT', NULL, 'attempts', 'auth', 'Wrong entries allowed before a one-time code is spent', 1, CURRENT_TIMESTAMP),
  ('auth.otpResendCooldownSeconds', '60'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'auth', 'Minimum wait before another one-time code is sent', 1, CURRENT_TIMESTAMP),
  ('devices.batteryAdvisoryPct', '90'::jsonb, 'PERCENT', NULL, 'percent', 'devices', 'Below this battery level the handover shows a charge-before-departure advisory', 1, CURRENT_TIMESTAMP),
  ('devices.minHandoverBatteryPct', '50'::jsonb, 'PERCENT', NULL, 'percent', 'devices', 'Below this battery level the handover requires manual confirmation', 1, CURRENT_TIMESTAMP),
  ('devices.currentPskVersion', '1'::jsonb, 'INT', NULL, NULL, 'devices', 'Current fleet channel key version (D-021)', 1, CURRENT_TIMESTAMP),
  ('devices.requireCurrentPskForCheckout', 'true'::jsonb, 'BOOL', NULL, NULL, 'devices', 'Block check-out of a device provisioned with an older channel key version', 1, CURRENT_TIMESTAMP),
  ('trips.defaultRequiredGuideCount', '1'::jsonb, 'INT', NULL, 'guides', 'trips', 'Guides a new trip requires unless set otherwise', 1, CURRENT_TIMESTAMP),
  ('trips.readinessChecklist', '[{"key":"devicesCharged","label":"Devices charged","mandatory":true},{"key":"gpsFixOnEveryUnit","label":"GPS fix on every unit","mandatory":true},{"key":"firstAidKit","label":"First-aid kit","mandatory":true},{"key":"weatherChecked","label":"Weather checked","mandatory":true},{"key":"emergencyContactsBriefed","label":"Emergency contacts briefed","mandatory":true}]'::jsonb, 'JSON', NULL, NULL, 'trips', 'Items on the guide readiness checklist before a trip starts', 1, CURRENT_TIMESTAMP),
  ('trips.requireReadinessBeforeStart', 'true'::jsonb, 'BOOL', NULL, NULL, 'trips', 'A trip cannot start until the readiness checklist passes', 1, CURRENT_TIMESTAMP),
  ('trips.bookingCloseHoursBeforeStart', '24'::jsonb, 'INT', NULL, 'hours', 'trips', 'Bookings close this many hours before the trip starts', 1, CURRENT_TIMESTAMP),
  ('rentals.customerHoldMinutes', '10'::jsonb, 'INT', NULL, 'minutes', 'rentals', 'How long a customer device reservation is held before it expires', 1, CURRENT_TIMESTAMP),
  ('rentals.maxDevicesPerCustomerBooking', '1'::jsonb, 'INT', NULL, 'devices', 'rentals', 'Most devices one customer booking may request', 1, CURRENT_TIMESTAMP),
  ('rentals.maxDevicesPerStaffBooking', '20'::jsonb, 'INT', NULL, 'devices', 'rentals', 'Most devices one staff or guide booking may request', 1, CURRENT_TIMESTAMP),
  ('rentals.allocationLeadHours', '12'::jsonb, 'INT', NULL, 'hours', 'rentals', 'Allocation window opens this many hours before the trip starts', 1, CURRENT_TIMESTAMP),
  ('rentals.allocationTrailHours', '24'::jsonb, 'INT', NULL, 'hours', 'rentals', 'Allocation window closes this many hours after the trip ends', 1, CURRENT_TIMESTAMP),
  ('rentals.nonReturnGraceDays', '3'::jsonb, 'INT', NULL, 'days', 'rentals', 'Days after the due time before an unreturned device is loss-suspected', 1, CURRENT_TIMESTAMP),
  ('rentals.reservationRetryLimit', '3'::jsonb, 'INT', NULL, 'attempts', 'rentals', 'Retries when a device reservation loses a race', 1, CURRENT_TIMESTAMP),
  ('rentals.requireSignedAgreementForCheckout', 'true'::jsonb, 'BOOL', NULL, NULL, 'rentals', 'Check-out requires a signed rental agreement', 1, CURRENT_TIMESTAMP),
  ('rentals.requireEscrowBeforeReview', 'true'::jsonb, 'BOOL', NULL, NULL, 'rentals', 'Operator review waits until the booking escrow is paid', 1, CURRENT_TIMESTAMP),
  ('rentals.agreementTerms', '{"version":"0","text":""}'::jsonb, 'JSON', NULL, NULL, 'rentals', 'Rental agreement terms: version and text', 1, CURRENT_TIMESTAMP),
  ('billing.freeCancellationMinutes', '10'::jsonb, 'INT', NULL, 'minutes', 'billing', 'A booking cancelled within this many minutes pays no fee', 1, CURRENT_TIMESTAMP),
  ('billing.cancellationFeePct', '5'::jsonb, 'PERCENT', NULL, 'percent', 'billing', 'Cancellation fee as a percentage of the rental fee', 1, CURRENT_TIMESTAMP),
  ('billing.lateGraceHours', '2'::jsonb, 'INT', NULL, 'hours', 'billing', 'Grace after the due time before a late fee starts', 1, CURRENT_TIMESTAMP),
  ('billing.lateFeePerDevicePerDay', '50000'::jsonb, 'DECIMAL', NULL, 'VND', 'billing', 'Late fee per device per started day after the grace', 1, CURRENT_TIMESTAMP),
  ('billing.waiverApprovalThreshold', '200000'::jsonb, 'DECIMAL', NULL, 'VND', 'billing', 'Fee waivers above this amount need a second operator', 1, CURRENT_TIMESTAMP),
  ('billing.sandboxFailureRate', '0'::jsonb, 'INT', NULL, NULL, 'billing', 'Demo switch: share of sandbox payments that fail', 1, CURRENT_TIMESTAMP),
  ('incidents.episodeWindowSeconds', '300'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'incidents', 'An SOS within this window of the last event joins the open episode', 1, CURRENT_TIMESTAMP),
  ('incidents.ackEscalationSeconds', '120'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'incidents', 'An unacknowledged incident escalates after this long', 1, CURRENT_TIMESTAMP),
  ('incidents.suspectedSuppressMinutes', '30'::jsonb, 'INT', NULL, 'minutes', 'incidents', 'After a dismissed suspected episode, suppress another for this long', 1, CURRENT_TIMESTAMP),
  ('incidents.notifyAdminsOnCreate', 'true'::jsonb, 'BOOL', NULL, NULL, 'incidents', 'Alert admins as well as operators when an incident opens', 1, CURRENT_TIMESTAMP),
  ('monitoring.deviceStaleSeconds', '120'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'monitoring', 'A device with no packet for this long is shown stale', 1, CURRENT_TIMESTAMP),
  ('monitoring.gatewayStaleSeconds', '120'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'monitoring', 'A gateway with no packet for this long is shown stale', 1, CURRENT_TIMESTAMP),
  ('monitoring.maxPlausibleSpeedKmh', '30'::jsonb, 'INT', NULL, 'km/h', 'monitoring', 'Positions implying a faster speed are not plotted', 1, CURRENT_TIMESTAMP),
  ('monitoring.batteryWarningPct', '30'::jsonb, 'PERCENT', NULL, 'percent', 'monitoring', 'Battery warning level on the live map', 1, CURRENT_TIMESTAMP),
  ('monitoring.batteryCriticalPct', '15'::jsonb, 'PERCENT', NULL, 'percent', 'monitoring', 'Battery critical level on the live map', 1, CURRENT_TIMESTAMP),
  ('monitoring.positionEmitMinIntervalMs', '1000'::jsonb, 'INT', NULL, 'milliseconds', 'monitoring', 'Minimum interval between position pushes per device', 1, CURRENT_TIMESTAMP),
  ('monitoring.staleSweepSeconds', '15'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'monitoring', 'Cadence of the staleness sweep job', 1, CURRENT_TIMESTAMP),
  ('gatewaySync.retroTagGraceSeconds', '60'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'gateway-sync', 'Positions this long before an SOS text are tagged into its episode', 1, CURRENT_TIMESTAMP),
  ('gatewaySync.cadenceCount', '6'::jsonb, 'INT', NULL, 'positions', 'gateway-sync', 'Positions inside the cadence window that raise a suspected episode', 1, CURRENT_TIMESTAMP),
  ('gatewaySync.cadenceWindowSeconds', '60'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'gateway-sync', 'Window for the cadence-anomaly count', 1, CURRENT_TIMESTAMP),
  ('gatewaySync.clockSkewToleranceSeconds', '300'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'gateway-sync', 'Device time this far in the future is flagged CLOCK_SKEW', 1, CURRENT_TIMESTAMP),
  ('gatewaySync.maxBacklogAgeHours', '72'::jsonb, 'INT', NULL, 'hours', 'gateway-sync', 'Device time older than this is flagged CLOCK_SKEW', 1, CURRENT_TIMESTAMP),
  ('gatewaySync.gatewaySilenceSeconds', '120'::jsonb, 'DURATION_SECONDS', NULL, 'seconds', 'gateway-sync', 'A silent gateway raises an alarm after this long', 1, CURRENT_TIMESTAMP);

INSERT INTO "roles" ("id", "key", "name", "accountType", "isSystem") VALUES
  (gen_random_uuid()::text, 'ADMIN', 'Admin', 'STAFF', true),
  (gen_random_uuid()::text, 'OPERATOR', 'Operator', 'STAFF', true),
  (gen_random_uuid()::text, 'GUIDE', 'Guide', 'STAFF', true),
  (gen_random_uuid()::text, 'CUSTOMER', 'Customer', 'CUSTOMER', true);

INSERT INTO "permissions" ("id", "key", "action", "subject", "conditions", "fields") VALUES
  (gen_random_uuid()::text, 'user.manage', 'manage', 'User', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'role.manage', 'manage', 'Role', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'permission.manage', 'manage', 'Permission', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'parameter.read', 'read', 'Parameter', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'parameter.update', 'update', 'Parameter', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'auditLog.read', 'read', 'AuditLog', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'hardwareVariant.manage', 'manage', 'HardwareVariant', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'device.read', 'read', 'Device', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'device.create', 'create', 'Device', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'device.update', 'update', 'Device', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'device.transition', 'transition', 'Device', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'maintenanceRecord.read', 'read', 'MaintenanceRecord', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'trekPackage.read', 'read', 'TrekPackage', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'trip.read', 'read', 'Trip', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'tripRequest.read', 'read', 'TripRequest', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.read', 'read', 'Booking', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.read', 'read', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rentalAgreement.read', 'read', 'RentalAgreement', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'invoice.read', 'read', 'Invoice', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'payment.read', 'read', 'Payment', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'pricingRule.manage', 'manage', 'PricingRule', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'damageFeeRule.manage', 'manage', 'DamageFeeRule', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'feeWaiver.read', 'read', 'FeeWaiver', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.read', 'read', 'Incident', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'gatewayEvent.read', 'read', 'GatewayEvent', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'syncAudit.read', 'read', 'SyncAudit', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'syncAudit.replay', 'replay', 'SyncAudit', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'monitoring.read', 'read', 'Monitoring', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'user.read', 'read', 'User', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'hardwareVariant.read', 'read', 'HardwareVariant', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'device.provision', 'provision', 'Device', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'maintenanceRecord.create', 'create', 'MaintenanceRecord', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'maintenanceRecord.update', 'update', 'MaintenanceRecord', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'trekPackage.manage', 'manage', 'TrekPackage', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'trip.manage', 'manage', 'Trip', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'trip.transition', 'transition', 'Trip', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'trip.assignGuide', 'assignGuide', 'Trip', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'tripRequest.update', 'update', 'TripRequest', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.manage', 'manage', 'Booking', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.confirm', 'confirm', 'Booking', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.reject', 'reject', 'Booking', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.cancel', 'cancel', 'Booking', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.extendHold', 'extendHold', 'Booking', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.manage', 'manage', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.allocate', 'allocate', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.checkout', 'checkout', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.checkin', 'checkin', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.inspect', 'inspect', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.cancel', 'cancel', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rental.close', 'close', 'Rental', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rentalAgreement.generate', 'generate', 'RentalAgreement', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'rentalAgreement.sign', 'sign', 'RentalAgreement', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'invoice.settle', 'settle', 'Invoice', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'payment.create', 'create', 'Payment', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'pricingRule.read', 'read', 'PricingRule', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'damageFeeRule.read', 'read', 'DamageFeeRule', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'feeWaiver.request', 'request', 'FeeWaiver', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.create', 'create', 'Incident', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.acknowledge', 'acknowledge', 'Incident', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.transition', 'transition', 'Incident', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.note', 'note', 'Incident', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.dismiss', 'dismiss', 'Incident', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'tripRequest.create', 'create', 'TripRequest', NULL, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.create.ownTrips', 'create', 'Booking', '{"tripId":{"$in":"${user.tripIds}"}}'::jsonb, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.read.ownTrips', 'read', 'Booking', '{"tripId":{"$in":"${user.tripIds}"}}'::jsonb, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.reserve.ownTrips', 'reserve', 'Booking', '{"tripId":{"$in":"${user.tripIds}"}}'::jsonb, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.read.ownTrips', 'read', 'Incident', '{"tripId":{"$in":"${user.tripIds}"}}'::jsonb, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.acknowledge.ownTrips', 'acknowledge', 'Incident', '{"tripId":{"$in":"${user.tripIds}"}}'::jsonb, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'incident.note.ownTrips', 'note', 'Incident', '{"tripId":{"$in":"${user.tripIds}"}}'::jsonb, ARRAY[]::text[]),
  (gen_random_uuid()::text, 'booking.create', 'create', 'Booking', NULL, ARRAY[]::text[]);

INSERT INTO "role_permissions" ("roleId", "permissionId")
SELECT r."id", p."id"
FROM (VALUES
  ('ADMIN', 'user.manage'),
  ('ADMIN', 'role.manage'),
  ('ADMIN', 'permission.manage'),
  ('ADMIN', 'parameter.read'),
  ('ADMIN', 'parameter.update'),
  ('ADMIN', 'auditLog.read'),
  ('ADMIN', 'hardwareVariant.manage'),
  ('ADMIN', 'device.read'),
  ('ADMIN', 'device.create'),
  ('ADMIN', 'device.update'),
  ('ADMIN', 'device.transition'),
  ('ADMIN', 'maintenanceRecord.read'),
  ('ADMIN', 'trekPackage.read'),
  ('ADMIN', 'trip.read'),
  ('ADMIN', 'tripRequest.read'),
  ('ADMIN', 'booking.read'),
  ('ADMIN', 'rental.read'),
  ('ADMIN', 'rentalAgreement.read'),
  ('ADMIN', 'invoice.read'),
  ('ADMIN', 'payment.read'),
  ('ADMIN', 'pricingRule.manage'),
  ('ADMIN', 'damageFeeRule.manage'),
  ('ADMIN', 'feeWaiver.read'),
  ('ADMIN', 'incident.read'),
  ('ADMIN', 'gatewayEvent.read'),
  ('ADMIN', 'syncAudit.read'),
  ('ADMIN', 'syncAudit.replay'),
  ('ADMIN', 'monitoring.read'),
  ('OPERATOR', 'user.read'),
  ('OPERATOR', 'parameter.read'),
  ('OPERATOR', 'hardwareVariant.read'),
  ('OPERATOR', 'device.read'),
  ('OPERATOR', 'device.create'),
  ('OPERATOR', 'device.update'),
  ('OPERATOR', 'device.transition'),
  ('OPERATOR', 'device.provision'),
  ('OPERATOR', 'maintenanceRecord.create'),
  ('OPERATOR', 'maintenanceRecord.update'),
  ('OPERATOR', 'trekPackage.manage'),
  ('OPERATOR', 'trip.manage'),
  ('OPERATOR', 'trip.transition'),
  ('OPERATOR', 'trip.assignGuide'),
  ('OPERATOR', 'tripRequest.read'),
  ('OPERATOR', 'tripRequest.update'),
  ('OPERATOR', 'booking.manage'),
  ('OPERATOR', 'booking.confirm'),
  ('OPERATOR', 'booking.reject'),
  ('OPERATOR', 'booking.cancel'),
  ('OPERATOR', 'booking.extendHold'),
  ('OPERATOR', 'rental.manage'),
  ('OPERATOR', 'rental.allocate'),
  ('OPERATOR', 'rental.checkout'),
  ('OPERATOR', 'rental.checkin'),
  ('OPERATOR', 'rental.inspect'),
  ('OPERATOR', 'rental.cancel'),
  ('OPERATOR', 'rental.close'),
  ('OPERATOR', 'rentalAgreement.generate'),
  ('OPERATOR', 'rentalAgreement.sign'),
  ('OPERATOR', 'invoice.read'),
  ('OPERATOR', 'invoice.settle'),
  ('OPERATOR', 'payment.create'),
  ('OPERATOR', 'pricingRule.read'),
  ('OPERATOR', 'damageFeeRule.read'),
  ('OPERATOR', 'feeWaiver.request'),
  ('OPERATOR', 'incident.read'),
  ('OPERATOR', 'incident.create'),
  ('OPERATOR', 'incident.acknowledge'),
  ('OPERATOR', 'incident.transition'),
  ('OPERATOR', 'incident.note'),
  ('OPERATOR', 'incident.dismiss'),
  ('OPERATOR', 'gatewayEvent.read'),
  ('OPERATOR', 'monitoring.read'),
  ('GUIDE', 'hardwareVariant.read'),
  ('GUIDE', 'trekPackage.read'),
  ('GUIDE', 'tripRequest.create'),
  ('GUIDE', 'booking.create.ownTrips'),
  ('GUIDE', 'booking.read.ownTrips'),
  ('GUIDE', 'booking.reserve.ownTrips'),
  ('GUIDE', 'incident.read.ownTrips'),
  ('GUIDE', 'incident.acknowledge.ownTrips'),
  ('GUIDE', 'incident.note.ownTrips'),
  ('CUSTOMER', 'booking.create')
) AS g ("roleKey", "permissionKey")
JOIN "roles" r ON r."key" = g."roleKey"
JOIN "permissions" p ON p."key" = g."permissionKey";
