from ._common import USER_ID, ORG_ID, NOW, ep, paged, PAGE_QUERY

ME = {"id": USER_ID, "email": "manager@acme-trek.vn", "fullName": "Nguyen Van A", "accountType": "ORGANIZATION",
      "roles": ["ORG_MANAGER"], "organization": {"id": ORG_ID, "code": "ORG-0007", "legalName": "ACME Trek Co., Ltd.",
                                                  "status": "ACTIVE", "memberRole": "MANAGER"}}
ACCOUNT = {"id": USER_ID, "email": "staff1@treklink.vn", "fullName": "Tran Thi B", "accountType": "TREKLINK",
           "roles": ["STAFF"], "isActive": True, "lastLoginAt": NOW, "createdAt": NOW}
TOKENS = {"accessToken": "eyJhbGciOiJIUzI1NiIs...", "accessTokenExpiresIn": 900,
          "refreshToken": "rt_7Zq...opaque", "refreshTokenExpiresIn": 1209600}
BAD_CODE = (400, "CODE_INVALID", "The code is wrong, expired, used or out of attempts",
            "This code is invalid or has expired. Request a new one.")
WEAK = (400, "PASSWORD_POLICY", "The new password breaks the policy (auth.passwordMinLength)",
        "password must be at least 8 characters.")

ENDPOINTS = [
    ep("POST", "/api/auth/login", "Sign in", "Public",
       "Exchanges email and password for a short-lived access token and a rotating refresh token. The "
       "response never says which field was wrong (FR-AUTH-02). Repeated failures lock the account for "
       "`auth.lockoutMinutes`.",
       "UC-08, FR-AUTH-02, FR-AUTH-08, MSG09",
       body=[["email", "Login email, case-insensitive", "string", "yes", "`manager@acme-trek.vn`"],
             ["password", "Password", "string", "yes", "`********`"]],
       sample={"email": "manager@acme-trek.vn", "password": "********"},
       response={**TOKENS, "user": ME}, message="Signed in",
       errors=[(401, "INVALID_CREDENTIALS", "Unknown email, wrong password, or inactive account",
                "Incorrect email or password. Please try again."),
               (423, "ACCOUNT_LOCKED", "Too many failures inside auth.loginFailureWindowMinutes",
                "Too many attempts. Try again in 15 minutes.")],
       steps=["Look up the user by lower-cased email", "bcrypt.compare in constant time",
              "Record AuthEvent LOGIN_SUCCEEDED or LOGIN_FAILED", "Open a refresh-token family, sign the access token"],
       controller="AuthController", service="AuthService", call="login(dto, ip, userAgent)",
       seq=["Svc->>DB: SELECT user, roles, membership", "Svc->>Svc: bcrypt.compare",
            "Svc->>DB: INSERT refresh_tokens, auth_events"]),

    ep("POST", "/api/auth/refresh", "Rotate tokens", "Public (refresh token)",
       "Issues a new access token and rotates the refresh token. Reusing an already rotated refresh token "
       "revokes its whole family (FR-AUTH-03). A deactivated account is refused (FR-AUTH-07).",
       "UC-08, FR-AUTH-03, FR-AUTH-07",
       body=[["refreshToken", "Opaque refresh token", "string", "yes", "`rt_7Zq...`"]],
       sample={"refreshToken": "rt_7Zq...opaque"}, response=TOKENS, message="Token refreshed",
       errors=[(401, "REFRESH_INVALID", "Unknown, expired or revoked refresh token, or inactive account",
                "Your session has ended. Please sign in again."),
               (401, "REFRESH_REUSED", "A rotated token was presented again; the family is revoked",
                "Your session has ended. Please sign in again.")],
       steps=["Hash and look up the token", "Revoke it, insert its successor in the same family",
              "Record AuthEvent TOKEN_REFRESHED"],
       controller="AuthController", service="TokenService", call="rotate(token)",
       seq=["Svc->>DB: SELECT refresh_tokens FOR UPDATE", "Svc->>DB: UPDATE revokedAt, INSERT successor"]),

    ep("POST", "/api/auth/logout", "Sign out", "Any signed-in user",
       "Revokes the presented refresh token immediately (FR-AUTH-04).", "UC-08, FR-AUTH-04",
       body=[["refreshToken", "The refresh token to revoke", "string", "yes", "`rt_7Zq...`"]],
       sample={"refreshToken": "rt_7Zq...opaque"}, response=None, message="Signed out",
       steps=["Revoke the token", "Record AuthEvent LOGOUT"],
       controller="AuthController", service="TokenService", call="revoke(token, caller)",
       seq=["Svc->>DB: UPDATE refresh_tokens SET revokedAt"]),

    ep("GET", "/api/auth/me", "Current account", "Any signed-in user",
       "Returns the caller's account, roles and, for an organization account, its organization and "
       "member role. The frontend builds its navigation from this.",
       "UC-08, FR-AUTH-10", response=ME,
       steps=["Read the user, roles and membership"],
       controller="AuthController", service="AuthService", call="me(caller)",
       seq=["Svc->>DB: SELECT user, roles, membership"]),

    ep("POST", "/api/auth/password/forgot", "Request a password reset", "Public",
       "Sends a single-use, time-limited code to the registered email. The response is identical whether "
       "or not the email exists (FR-AUTH-05).",
       "UC-09, FR-AUTH-05, BR-35",
       body=[["email", "Account email", "string", "yes", "`manager@acme-trek.vn`"]],
       sample={"email": "manager@acme-trek.vn"}, response=None,
       message="If the email is registered, a code has been sent.",
       errors=[(429, "OTP_COOLDOWN", "A code was sent less than auth.otpResendCooldownSeconds ago",
                "Please wait a minute before requesting another code.")],
       steps=["Look up the user", "If found and active: store the code hash, email the code",
              "Record AuthEvent PASSWORD_RESET_REQUESTED", "Answer identically either way"],
       controller="PasswordController", service="PasswordService", call="forgot(email)",
       participants=[["Mail", "Email service"]],
       seq=["Svc->>DB: INSERT one_time_codes", "Svc-)Mail: send code"]),

    ep("POST", "/api/auth/password/reset", "Reset the password with a code", "Public",
       "Sets a new password with the emailed code, then revokes every refresh-token family of the account.",
       "UC-09, FR-AUTH-05, MSG08",
       body=[["email", "Account email", "string", "yes", "`manager@acme-trek.vn`"],
             ["code", "Six-digit code", "string", "yes", "`482913`"],
             ["newPassword", "New password", "string", "yes", "`********`"]],
       sample={"email": "manager@acme-trek.vn", "code": "482913", "newPassword": "********"},
       response=None, message="Password changed", errors=[BAD_CODE, WEAK],
       steps=["Verify the code hash, attempts and expiry", "bcrypt-hash the new password",
              "Consume the code, revoke all refresh tokens", "Record AuthEvent PASSWORD_RESET_COMPLETED"],
       controller="PasswordController", service="PasswordService", call="reset(dto)",
       seq=["Svc->>DB: SELECT one_time_codes FOR UPDATE", "Svc->>DB: UPDATE users, one_time_codes, refresh_tokens"]),

    ep("POST", "/api/auth/password/set", "Accept an invitation", "Public",
       "Sets the first password of an invited account (organization member, or TrekLink Staff created by an "
       "Admin) with the invitation code, and signs the user in.",
       "UC-04, UC-10, FR-ORG-04, MSG08",
       body=[["email", "Invited email", "string", "yes", "`operator@acme-trek.vn`"],
             ["code", "Invitation code from the email", "string", "yes", "`739104`"],
             ["password", "New password", "string", "yes", "`********`"]],
       sample={"email": "operator@acme-trek.vn", "code": "739104", "password": "********"},
       response={**TOKENS, "user": {**ME, "roles": ["ORG_OPERATOR"]}}, message="Welcome to TrekLink",
       errors=[BAD_CODE, WEAK],
       steps=["Verify the SET_PASSWORD code", "Store the bcrypt hash", "Record AuthEvent PASSWORD_SET",
              "Issue tokens"],
       controller="PasswordController", service="PasswordService", call="setFirst(dto)",
       seq=["Svc->>DB: UPDATE users, one_time_codes", "Svc->>DB: INSERT refresh_tokens"]),

    ep("POST", "/api/auth/password/change", "Change own password", "Any signed-in user",
       "Changes the caller's password after checking the current one; other sessions are revoked.",
       "UC-08, FR-AUTH-02",
       body=[["currentPassword", "Current password", "string", "yes", "`********`"],
             ["newPassword", "New password", "string", "yes", "`********`"]],
       sample={"currentPassword": "********", "newPassword": "********"}, response=None, message="Password changed",
       errors=[(400, "INVALID_CREDENTIALS", "The current password is wrong", "The current password is incorrect."), WEAK],
       steps=["Verify the current password", "Store the new hash", "Revoke other refresh-token families"],
       controller="PasswordController", service="PasswordService", call="change(dto, caller)",
       seq=["Svc->>DB: UPDATE users, refresh_tokens"]),

    ep("GET", "/api/accounts", "List TrekLink accounts", "TrekLink Admin",
       "Lists TrekLink Staff and Admin accounts (UC-10). Organization accounts are managed by their "
       "Manager through the organizations module.",
       "UC-10, FR-AUTH-06",
       query=[["q", "Name or email contains", "string", "no", "`tran`"],
              ["isActive", "Filter by active flag", "bool", "no", "`true`"]] + PAGE_QUERY,
       response=paged(ACCOUNT, 4), steps=["Read accounts of type TREKLINK"],
       controller="AccountsController", service="AccountsService", call="list(query)",
       seq=["Svc->>DB: SELECT users WHERE accountType = TREKLINK"]),

    ep("POST", "/api/accounts", "Create a TrekLink account", "TrekLink Admin",
       "Creates a TrekLink Staff or Admin account and emails an invitation code; the account has no "
       "password until the code is used (FR-AUTH-05: nobody sets another person's password).",
       "UC-10, FR-AUTH-06, BR-35, MSG10",
       body=[["email", "Work email", "string", "yes", "`staff2@treklink.vn`"],
             ["fullName", "Full name", "string", "yes", "`Le Van C`"],
             ["role", "`STAFF` or `ADMIN`", "enum", "yes", "`STAFF`"]],
       sample={"email": "staff2@treklink.vn", "fullName": "Le Van C", "role": "STAFF"},
       response={**ACCOUNT, "email": "staff2@treklink.vn", "fullName": "Le Van C", "lastLoginAt": None},
       status=201, message="Account created, invitation sent",
       errors=[(409, "CONFLICT_UNIQUE", "The email is already registered", "staff2@treklink.vn is already registered.")],
       steps=["Insert the user and role", "Store a SET_PASSWORD code hash", "Email the invitation",
              "Emit audit.record account.create"],
       controller="AccountsController", service="AccountsService", call="create(dto, actor)",
       participants=[["Mail", "Email service"]],
       seq=["Svc->>DB: INSERT users, user_roles, one_time_codes", "Svc-)Mail: invitation"]),

    ep("PATCH", "/api/accounts/:id", "Edit a TrekLink account", "TrekLink Admin",
       "Changes the name, phone or role of a TrekLink account. A role change takes effect on the next "
       "request (FR-AUTH-06). An Admin cannot remove their own Admin role.",
       "UC-10, FR-AUTH-06",
       path=[["id", "Account id", "uuid", f"`{USER_ID}`"]],
       body=[["fullName", "Full name", "string", "no", "`Tran Thi B`"],
             ["phoneNumber", "Phone", "string", "no", "`0901234567`"],
             ["role", "`STAFF` or `ADMIN`", "enum", "no", "`ADMIN`"]],
       sample={"role": "ADMIN"}, response={**ACCOUNT, "roles": ["ADMIN"]}, message="Account updated",
       entity="Account",
       errors=[(409, "SELF_DEMOTION", "An Admin tried to remove their own Admin role",
                "You cannot remove your own Admin role.")],
       steps=["Update the fields and role", "Emit audit.record account.update"],
       controller="AccountsController", service="AccountsService", call="update(id, dto, actor)",
       seq=["Svc->>DB: UPDATE users, user_roles"]),

    ep("POST", "/api/accounts/:id/deactivate", "Deactivate a TrekLink account", "TrekLink Admin",
       "Deactivates the account and revokes its refresh tokens immediately (FR-AUTH-07). The last active "
       "Admin cannot be deactivated.",
       "UC-10, FR-AUTH-07, FR-AUTH-09",
       path=[["id", "Account id", "uuid", f"`{USER_ID}`"]],
       body=[["reason", "Why", "string", "yes", "`Left the company`"]],
       sample={"reason": "Left the company"}, response={**ACCOUNT, "isActive": False}, message="Account deactivated",
       entity="Account",
       errors=[(409, "LAST_ADMIN", "This is the last active Admin", "At least one Admin must stay active.")],
       steps=["Set isActive false", "Revoke all refresh tokens", "Record AuthEvent ACCOUNT_DEACTIVATED"],
       controller="AccountsController", service="AccountsService", call="deactivate(id, dto, actor)",
       seq=["Svc->>DB: UPDATE users, refresh_tokens; INSERT auth_events"]),

    ep("POST", "/api/accounts/:id/reactivate", "Reactivate a TrekLink account", "TrekLink Admin",
       "Reactivates a deactivated TrekLink account.", "UC-10, FR-AUTH-07",
       path=[["id", "Account id", "uuid", f"`{USER_ID}`"]], response=ACCOUNT, message="Account reactivated",
       entity="Account", steps=["Set isActive true", "Record AuthEvent ACCOUNT_REACTIVATED"],
       controller="AccountsController", service="AccountsService", call="reactivate(id, actor)",
       seq=["Svc->>DB: UPDATE users; INSERT auth_events"]),

    ep("POST", "/api/accounts/:id/password-reset", "Trigger a password reset", "TrekLink Staff, TrekLink Admin",
       "Sends a reset code to the account's own email. Staff can trigger it for any account but never see "
       "or set the password (BR-35).",
       "UC-09, FR-AUTH-05, BR-35",
       path=[["id", "Account id, TrekLink or organization", "uuid", f"`{USER_ID}`"]], response=None,
       message="Reset code sent to the account email", entity="Account",
       steps=["Store a PASSWORD_RESET code hash", "Email the code to the account", "Emit audit.record"],
       controller="AccountsController", service="PasswordService", call="triggerReset(id, actor)",
       participants=[["Mail", "Email service"]],
       seq=["Svc->>DB: INSERT one_time_codes", "Svc-)Mail: send code"]),

    ep("GET", "/api/roles", "List roles and permissions", "TrekLink Admin",
       "Lists the four system roles with their permissions as data (FR-AUTH-06).", "UC-10, FR-AUTH-06",
       response=[{"id": "r-1", "key": "ORG_OPERATOR", "accountType": "ORGANIZATION", "isSystem": True,
                  "permissions": [{"key": "incident.acknowledge.ownOrganization", "action": "acknowledge",
                                   "subject": "Incident", "conditions": {"organizationId": "${user.organizationId}"}}]}],
       steps=["Read roles with permissions"],
       controller="RolesController", service="RolesService", call="list()",
       seq=["Svc->>DB: SELECT roles, role_permissions, permissions"]),

    ep("PUT", "/api/roles/:id/permissions", "Replace a role's permissions", "TrekLink Admin",
       "Replaces the permission set of a role. The change applies on the next request, without a redeploy "
       "(FR-AUTH-06). Removing `role.manage` from ADMIN is refused.",
       "UC-10, FR-AUTH-06",
       path=[["id", "Role id", "uuid", "`r-1`"]],
       body=[["permissionKeys", "Full list of permission keys", "string[]", "yes",
              "`[\"incident.acknowledge.ownOrganization\"]`"]],
       sample={"permissionKeys": ["incident.read.ownOrganization", "incident.acknowledge.ownOrganization"]},
       response={"id": "r-1", "key": "ORG_OPERATOR", "permissionCount": 2}, message="Permissions updated",
       entity="Role",
       errors=[(400, "UNKNOWN_PERMISSION", "A key is not in the permission catalogue", "Unknown permission: x."),
               (409, "ADMIN_LOCKOUT", "The change would remove role.manage from ADMIN",
                "Admins must keep the right to manage roles.")],
       steps=["Validate the keys", "Replace role_permissions in one transaction", "Bump the policy cache version",
              "Emit audit.record role.permissions"],
       controller="RolesController", service="RolesService", call="replacePermissions(id, dto, actor)",
       seq=["Svc->>DB: DELETE + INSERT role_permissions", "Svc-)Svc: emit policy.changed"]),

    ep("GET", "/api/auth-events", "Authentication audit", "TrekLink Admin",
       "Searches the append-only authentication log by account, type and time (FR-AUTH-08).",
       "UC-58, FR-AUTH-08",
       query=[["userId", "Account", "uuid", "no", f"`{USER_ID}`"],
              ["type", "AuthEventType", "enum", "no", "`LOGIN_FAILED`"],
              ["from", "Inclusive start", "datetime", "no", "`2026-10-01T00:00:00Z`"],
              ["to", "Exclusive end", "datetime", "no", "`2026-10-21T00:00:00Z`"]] + PAGE_QUERY,
       response=paged({"id": "e-1", "userId": USER_ID, "email": "manager@acme-trek.vn", "type": "LOGIN_FAILED",
                       "ip": "203.0.113.7", "createdAt": NOW}),
       steps=["Read auth_events newest first"],
       controller="AuthEventsController", service="AuthEventsService", call="search(query)",
       seq=["Svc->>DB: SELECT auth_events"]),
]
