from ._common import (USER_ID, ORG_ID, DEVICE_ID, VARIANT_ID, CONTRACT_ID, NOW, ep, paged, PAGE_QUERY,
                      state_409, STALE)

CONTRACT = {"id": CONTRACT_ID, "code": "RC-2026-0042", "organization": {"id": ORG_ID, "code": "ORG-0007",
                                                                        "legalName": "ACME Trek Co., Ltd."},
            "planType": "MONTHLY", "dayPlanDays": None, "hardwareVariant": {"id": VARIANT_ID, "code": "treklink-v3"},
            "quantity": 10, "requestedStartDate": "2026-10-25", "monthlyUnitPriceVnd": 450000, "dayPremium": None,
            "holdingFeeRatio": 0.5, "status": "ACTIVE", "statusChangedAt": NOW, "handedOverAt": NOW,
            "currentTerm": {"seq": 1, "startsAt": "2026-10-25T02:00:00Z", "endsAt": "2026-11-25T02:00:00Z"},
            "endsAt": None, "noticeGivenAt": None, "returnDueAt": None, "version": 4}
CDEV = {"deviceId": DEVICE_ID, "assetTag": "TL-0042", "handedOverAt": NOW, "checkedInAt": None, "lostAt": None,
        "holder": {"name": "Le Thi E", "phone": "0912345678", "emergencyContact": "Le Van F, 0987654321"}}
C_PATH = ["id", "Contract id; members may use only their own organization's", "uuid", f"`{CONTRACT_ID}`"]
D_PATH = ["deviceId", "Device committed to the contract", "uuid", f"`{DEVICE_ID}`"]
VERSION = ["expectedVersion", "Contract version the caller saw", "int", "yes", "`4`"]
NOT_ON = (409, "DEVICE_NOT_ON_CONTRACT", "The device is not committed to this contract",
          "TL-0042 does not belong to contract RC-2026-0042.")

ENDPOINTS = [
    ep("POST", "/api/contracts", "Request a rental contract", "Org Manager: own",
       "Requests a plan: monthly, or a day plan of a configured length; one hardware variant; a quantity "
       "at or above the minimum order quantity; a start date. Prices are snapshotted now, so a later price "
       "change does not affect this contract (FR-CFG-02). The organization must be `ACTIVE`.",
       "UC-15, FR-CON-01, FR-CON-02, FR-CON-07, FR-BILL-01, FR-BILL-02, BR-01, BR-02, E01-2, E01-3, MSG13, MSG14",
       body=[["planType", "`MONTHLY` or `DAY`", "enum", "yes", "`MONTHLY`"],
             ["dayPlanDays", "One of rentals.dayPlanLengths; DAY only", "int", "cond.", "`4`"],
             ["hardwareVariantId", "Active variant", "uuid", "yes", f"`{VARIANT_ID}`"],
             ["quantity", "At least rentals.minOrderQuantity", "int", "yes", "`10`"],
             ["requestedStartDate", "Handover day, not in the past", "date", "yes", "`2026-10-25`"]],
       sample={"planType": "MONTHLY", "hardwareVariantId": VARIANT_ID, "quantity": 10, "requestedStartDate": "2026-10-25"},
       response={**CONTRACT, "status": "REQUESTED", "handedOverAt": None, "currentTerm": None, "version": 0,
                 "quote": {"firstPaymentVnd": 2250000, "termFeeVnd": 4500000}},
       status=201, message="Request sent. TrekLink will confirm availability and your handover appointment.",
       errors=[(400, "BELOW_MOQ", "Quantity below rentals.minOrderQuantity", "The minimum order is 5 devices."),
               (400, "DAY_PLAN_LENGTH", "dayPlanDays is not a configured length", "Choose a plan of 3, 4 or 7 days."),
               (409, "ORGANIZATION_NOT_ACTIVE", "The organization is PENDING, REJECTED, SUSPENDED or CLOSED",
                "Your organization cannot request devices while it is SUSPENDED.")],
       steps=["Require the organization ACTIVE", "Validate plan, variant, quantity and date",
              "Snapshot price, premium and holding ratio from billing", "Insert the contract REQUESTED",
              "Notify TrekLink Staff"],
       controller="ContractsController", service="ContractsService", call="request(dto, caller)",
       participants=[["Org", "OrganizationsService"], ["Bill", "BillingService"]],
       seq=["Svc->>Org: assertActive(orgId)", "Svc->>Bill: priceSnapshot(variantId)",
            "Svc->>DB: INSERT rental_contracts, contract_transitions"]),

    ep("GET", "/api/contracts", "List contracts", "Org Manager, Org Operator: own; TrekLink Staff, TrekLink Admin",
       "Lists contracts. The Staff approval queue is `status=REQUESTED`; the handover queue is `APPROVED`.",
       "UC-55, FR-AUTH-11",
       query=[["status", "ContractStatus, repeatable", "enum", "no", "`REQUESTED`"],
              ["organizationId", "TrekLink staff only", "uuid", "no", f"`{ORG_ID}`"],
              ["planType", "Plan", "enum", "no", "`DAY`"]] + PAGE_QUERY,
       response=paged(CONTRACT, 3), steps=["Apply scope", "Read contracts"],
       controller="ContractsController", service="ContractsService", call="list(query, caller)",
       seq=["Svc->>DB: SELECT rental_contracts WHERE scope"]),

    ep("GET", "/api/contracts/:id", "Contract detail", "Org Manager, Org Operator: own; TrekLink Staff, TrekLink Admin",
       "Returns the contract with its terms, committed devices (with holder labels) and balance summary.",
       "UC-55, FR-AUTH-11, FR-CON-07",
       path=[C_PATH], response={**CONTRACT, "terms": [{"seq": 1, "startsAt": "2026-10-25T02:00:00Z",
                                                       "endsAt": "2026-11-25T02:00:00Z", "status": "OPEN"}],
                                "devices": [CDEV], "balance": {"dueNowVnd": 0, "dueLaterVnd": 2250000}},
       entity="Contract", steps=["Read within scope", "Ask billing for the balance summary"],
       controller="ContractsController", service="ContractsService", call="get(id, caller)",
       participants=[["Bill", "BillingService"]],
       seq=["Svc->>DB: SELECT contract, terms, contract_devices", "Svc->>Bill: balanceSummary(id)"]),

    ep("POST", "/api/contracts/:id/approve", "Approve a contract", "TrekLink Staff, TrekLink Admin",
       "Reserves exactly the requested number of `AVAILABLE` devices of the variant in one transaction "
       "holding row locks, moves them to `RESERVED` and the contract to `APPROVED`, and sets the "
       "reservation expiry. Fewer available devices refuse the approval: never over-allocated "
       "(FR-CON-03, BR-03, E01-1). Staff may name the devices; otherwise the oldest-checked ones are taken.",
       "UC-16, UC-17, FR-CON-03, FR-CON-11, FR-DEV-01, BR-03, BR-04, E01-1, MSG11",
       path=[C_PATH],
       body=[["deviceIds", "Optional explicit choice, length = quantity", "uuid[]", "no", "`[...]`"],
             ["handoverAt", "Appointment at the counter", "datetime", "yes", "`2026-10-25T02:00:00Z`"], VERSION],
       sample={"handoverAt": "2026-10-25T02:00:00Z", "expectedVersion": 0},
       response={**CONTRACT, "status": "APPROVED", "handedOverAt": None,
                 "reservationExpiresAt": "2026-10-27T02:00:00Z", "devices": [{**CDEV, "handedOverAt": None, "holder": None}]},
       message="Contract approved", entity="Contract",
       errors=[(409, "INSUFFICIENT_DEVICES", "Fewer AVAILABLE devices of the variant than requested",
                "Only 7 treklink-v3 devices are available. Lower the quantity or choose another variant."),
               state_409("contract", "APPROVED"), STALE],
       steps=["Lock the contract", "SELECT AVAILABLE devices of the variant FOR UPDATE SKIP LOCKED LIMIT quantity",
              "Insert contract_devices, move devices to RESERVED", "Move the contract to APPROVED",
              "Create term 1 from the requested start date and issue its invoice through billing",
              "Notify the Manager with the appointment"],
       controller="ContractsController", service="ContractLifecycleService", call="approve(id, dto, actor)",
       participants=[["Dev", "DevicesService"], ["Bill", "BillingService"]],
       seq=["Svc->>DB: BEGIN, SELECT contract FOR UPDATE",
            "Svc->>Dev: reserve(variantId, quantity, contractId, tx)", "Dev->>DB: SELECT ... FOR UPDATE SKIP LOCKED",
            "Svc->>Bill: issueFirstInvoice(contract, tx)", "Svc->>DB: UPDATE contract, INSERT transition, COMMIT"]),

    ep("POST", "/api/contracts/:id/reject", "Reject a contract request", "TrekLink Staff, TrekLink Admin",
       "Rejects a `REQUESTED` contract with a reason shown to the Manager (MSG16).", "UC-17, D-035, MSG16",
       path=[C_PATH], body=[["reason", "Reason", "string", "yes", "`Variant out of stock until November`"], VERSION],
       sample={"reason": "treklink-v4 is out of stock until November.", "expectedVersion": 0},
       response={**CONTRACT, "status": "REJECTED"}, message="Contract rejected", entity="Contract",
       errors=[state_409("contract", "APPROVED"), STALE], steps=["Require REQUESTED", "Move to REJECTED", "Notify the Manager"],
       controller="ContractsController", service="ContractLifecycleService", call="reject(id, dto, actor)",
       seq=["Svc->>DB: UPDATE contract, INSERT transition"]),

    ep("POST", "/api/contracts/:id/cancel", "Cancel before handover", "Org Manager: own; TrekLink Staff, TrekLink Admin",
       "Cancels a `REQUESTED` or `APPROVED` contract before handover and releases its devices to "
       "`AVAILABLE`. A holding fee already paid is retained; nothing else is charged (FR-CON-04, E01-7, MSG15).",
       "UC-18, FR-CON-04, E01-7, MSG15",
       path=[C_PATH], body=[["reason", "Reason", "string", "yes", "`Tour cancelled`"], VERSION],
       sample={"reason": "Our tour was cancelled.", "expectedVersion": 1},
       response={**CONTRACT, "status": "CANCELLED", "retainedVnd": 2250000}, message="Contract cancelled. Retained: 2,250,000 VND.",
       entity="Contract", errors=[state_409("contract", "ACTIVE"), STALE],
       steps=["Require REQUESTED or APPROVED", "Release contract_devices, move devices to AVAILABLE",
              "Void unpaid first-invoice lines through billing", "Move to CANCELLED"],
       controller="ContractsController", service="ContractLifecycleService", call="cancel(id, dto, caller)",
       participants=[["Dev", "DevicesService"], ["Bill", "BillingService"]],
       seq=["Svc->>Dev: release(contractId, tx)", "Svc->>Bill: settleCancellation(contract, tx)",
            "Svc->>DB: UPDATE contract, INSERT transition"]),

    ep("POST", "/api/contracts/:id/devices/:deviceId/swap", "Swap a reserved device", "TrekLink Staff",
       "A reserved device fails its check at handover: it goes to `MAINTENANCE` and another `AVAILABLE` "
       "device of the variant takes its place (E01-5). With no replacement available the handover is held.",
       "UC-20, FR-CON-05, FR-DEV-08, E01-5, MSG17",
       path=[C_PATH, D_PATH],
       body=[["reason", "What failed", "string", "yes", "`No GPS fix`"],
             ["replacementDeviceId", "Optional explicit replacement", "uuid", "no", "`...`"]],
       sample={"reason": "No GPS fix at the counter"},
       response={"released": {"deviceId": DEVICE_ID, "assetTag": "TL-0042", "status": "MAINTENANCE"},
                 "reserved": {"deviceId": "8f9e...", "assetTag": "TL-0051", "status": "RESERVED"}},
       message="Device swapped", entity="Contract",
       errors=[NOT_ON, (409, "INSUFFICIENT_DEVICES", "No AVAILABLE replacement of the variant",
                        "Only 0 treklink-v3 devices are available. Lower the quantity or choose another variant."),
               state_409("contract", "ACTIVE")],
       steps=["Require APPROVED", "Release the row, open maintenance on the failed device",
              "Reserve a replacement in the same transaction"],
       controller="ContractsController", service="ContractLifecycleService", call="swap(id, deviceId, dto, actor)",
       participants=[["Dev", "DevicesService"]],
       seq=["Svc->>Dev: failHandoverCheck(deviceId, tx)", "Svc->>Dev: reserve(variantId, 1, contractId, tx)"]),

    ep("GET", "/api/contracts/:id/handover-note/preview", "Preview the handover note", "TrekLink Staff",
       "Renders the handover note PDF without a signature, for the Manager to read at the counter before "
       "signing (FR-CON-06).", "UC-21, FR-CON-06",
       path=[C_PATH], response={"pdfBase64": "JVBERi0xLjcK...", "sha256": None},
       notes="Returns `application/json` with the PDF as base64 so the envelope holds.",
       entity="Contract", errors=[state_409("contract", "REQUESTED")],
       steps=["Require APPROVED", "Render organization, plan, term dates and every device by asset tag"],
       controller="ContractsController", service="HandoverNoteService", call="preview(id)",
       seq=["Svc->>DB: SELECT contract, devices, organization", "Svc->>Svc: render PDF"]),

    ep("POST", "/api/contracts/:id/devices/:deviceId/provisioning", "Record provisioning", "TrekLink Staff",
       "Records that the organization's channel key, at its current version, was written to a device "
       "reserved to this contract, at the counter. Only the version and the organization are stored; the key "
       "is never stored, shown, returned or logged (FR-DEV-05, NFR-SEC-06, NFR-IF-03).",
       "UC-14, FR-DEV-05, BR-09, NFR-IF-03",
       path=[C_PATH, D_PATH], body=[["keyVersion", "Must equal the organization's channelKeyVersion", "int", "yes", "`1`"]],
       sample={"keyVersion": 1},
       response={"deviceId": DEVICE_ID, "assetTag": "TL-0042", "status": "RESERVED", "keyVersion": 1,
                 "keyOrganizationId": ORG_ID, "provisionedAt": NOW}, status=201, message="Provisioning recorded",
       entity="Contract",
       errors=[NOT_ON, (409, "KEY_VERSION_MISMATCH", "keyVersion differs from the organization's current version",
                        "Provision this device with the organization's key before handover."),
               state_409("contract", "REQUESTED")],
       steps=["Require APPROVED and the device reserved to it", "Read the organization's key version",
              "DevicesService.recordProvisioning in one transaction"],
       controller="ContractsController", service="HandoverService", call="provision(id, deviceId, dto, actor)",
       participants=[["Org", "OrganizationsService"], ["Dev", "DevicesService"]],
       seq=["Svc->>Org: channelKeyVersion(orgId)", "Svc->>Dev: recordProvisioning(deviceId, orgId, keyVersion, tx)"]),

    ep("POST", "/api/contracts/:id/handover", "Complete the handover", "TrekLink Staff",
       "Completes the handover at the counter. Requires the first payment confirmed, the Manager's identity "
       "checked, every reserved device provisioned with the organization's current key and its handover "
       "check passed, and the drawn signature. Stamps the signature into the note, stores the PDF and its "
       "SHA-256, then moves the contract to `ACTIVE` and its devices to `RENTED` in one "
       "transaction (FR-CON-05, FR-CON-06, BR-09, D-037).",
       "UC-20, UC-21, FR-CON-05, FR-CON-06, FR-DEV-01, FR-DEV-05, BR-09, E01-4, MSG06, MSG19, MSG23, MSG24",
       path=[C_PATH],
       body=[["signedByMemberId", "Org Manager signing", "uuid", "yes", f"`{USER_ID}`"],
             ["identityChecked", "Document type and last digits seen", "string", "yes", "`CCCD ...4821`"],
             ["signaturePng", "Drawn signature, base64 PNG", "string", "yes", "`iVBORw0KGgo...`"],
             ["deviceChecks", "Per device: batteryPct and gpsFixOk at the counter", "object[]", "yes", "see sample"],
             ["acknowledgeLowBattery", "Proceed although a battery is below devices.handoverMinBatteryPct", "bool", "no", "`false`"],
             VERSION],
       sample={"signedByMemberId": USER_ID, "identityChecked": "CCCD ...4821", "signaturePng": "iVBORw0KGgo...",
               "deviceChecks": [{"deviceId": DEVICE_ID, "batteryPct": 96, "gpsFixOk": True}], "expectedVersion": 2},
       response={**CONTRACT, "handoverNoteSha256": "9f2c...e1", "devices": [CDEV]},
       message="Handover complete. 10 devices issued under contract RC-2026-0042.", entity="Contract",
       errors=[(409, "FIRST_PAYMENT_MISSING", "The holding fee or day-plan fee is not confirmed",
                "The first payment is not recorded yet."),
               (409, "DEVICE_NOT_PROVISIONED", "A device lacks provisioning at the current key version",
                "Provision this device with the organization's key before handover."),
               (409, "DEVICE_CHECK_FAILED", "A device check failed; swap it first", "This device cannot be allocated while it is MAINTENANCE."),
               (409, "LOW_BATTERY", "A battery is below the minimum and not acknowledged", "Battery 41 %. Charge before use."),
               (409, "BEFORE_START_DATE", "The requested start date has not come yet", "Handover is possible from 2026-10-25."),
               (400, "SIGNER_NOT_MANAGER", "The signer is not an active Manager of the organization",
                "Only a Manager of the organization can sign."),
               state_409("contract", "REQUESTED"), STALE],
       steps=["Require APPROVED and the first payment confirmed", "Check every device provisioned and passing",
              "Stamp the signature into the PDF, store it and its hash",
              "Move devices to RENTED and the contract to ACTIVE in one transaction", "Emit contract.activated"],
       controller="ContractsController", service="HandoverService", call="complete(id, dto, actor)",
       participants=[["Bill", "BillingService"], ["Dev", "DevicesService"], ["Store", "File storage"]],
       seq=["Svc->>Bill: firstPaymentConfirmed(id)", "Svc->>Dev: assertReadyForHandover(ids, keyVersion)",
            "Svc->>Store: put(note.pdf)", "Svc->>DB: BEGIN, UPDATE contract_devices",
            "Svc->>Dev: markRented(ids, tx)", "Svc->>DB: UPDATE contract, INSERT transition, COMMIT"]),

    ep("GET", "/api/contracts/:id/handover-note", "Download the signed handover note",
       "Org Manager: own; TrekLink Staff, TrekLink Admin",
       "Returns the signed PDF and its stored SHA-256; the hash is recomputed on read and a mismatch is "
       "reported, never repaired (FR-CON-06).", "UC-21, FR-CON-06",
       path=[C_PATH], response={"pdfBase64": "JVBERi0xLjcK...", "sha256": "9f2c...e1", "integrity": "OK"},
       entity="Contract", errors=[(409, "NOTE_NOT_SIGNED", "No signed note exists yet", "The handover is not complete yet.")],
       steps=["Load the PDF", "Recompute and compare the hash"],
       controller="ContractsController", service="HandoverNoteService", call="download(id, caller)",
       participants=[["Store", "File storage"]], seq=["Svc->>Store: get(path)", "Svc->>Svc: sha256 compare"]),

    ep("POST", "/api/contracts/:id/notice", "Give notice", "Org Manager: own",
       "Gives notice on a running monthly contract: it moves to `ENDING`, effective at the current term's "
       "end, when the devices fall due (FR-CON-09, BR-08, MSG18). A day plan cannot take notice.",
       "UC-23, FR-CON-09, BR-08, MSG18",
       path=[C_PATH], body=[VERSION], sample={"expectedVersion": 4},
       response={**CONTRACT, "status": "ENDING", "noticeGivenAt": NOW, "endsAt": "2026-11-25T02:00:00Z"},
       message="Notice recorded. The contract ends on 2026-11-25; 2,250,000 VND is due then.", entity="Contract",
       errors=[(409, "DAY_PLAN_NO_NOTICE", "The contract is a day plan", "A day plan ends on its own end date."),
               state_409("contract", "ENDING"), STALE],
       steps=["Require MONTHLY and ACTIVE", "Set endsAt to the current term end", "Move to ENDING"],
       controller="ContractsController", service="ContractLifecycleService", call="giveNotice(id, dto, caller)",
       seq=["Svc->>DB: UPDATE contract, INSERT transition"]),

    ep("PUT", "/api/contracts/:id/devices/:deviceId/holder", "Label a device holder",
       "Org Manager, Org Operator: own",
       "Sets or clears the optional holder label (name, phone, emergency contact) shown on the map and in "
       "alerts for this device. Labels are erased when the contract closes (FR-CON-14, BR-33, NFR-LEG-02).",
       "UC-25, FR-CON-14, BR-33",
       path=[C_PATH, D_PATH],
       body=[["name", "Holder name; null clears the label", "string", "no", "`Le Thi E`"],
             ["phone", "Holder phone", "string", "no", "`0912345678`"],
             ["emergencyContact", "Name and phone", "string", "no", "`Le Van F, 0987654321`"]],
       sample={"name": "Le Thi E", "phone": "0912345678", "emergencyContact": "Le Van F, 0987654321"},
       response=CDEV, message="Saved.", entity="Contract",
       errors=[NOT_ON, state_409("contract", "CLOSED")],
       steps=["Require the device handed over and not checked in", "Update the label", "Emit device.label.changed"],
       controller="ContractsController", service="ContractsService", call="labelHolder(id, deviceId, dto, caller)",
       seq=["Svc->>DB: UPDATE contract_devices"]),

    ep("POST", "/api/contracts/:id/check-ins", "Check devices in", "TrekLink Staff",
       "Checks returned devices in at the counter by asset tag. Each moves to `RETURNED`, its live data "
       "stops reaching the organization (FR-MON-08), and late days are charged when it comes back after "
       "the end plus the grace (FR-BILL-03). When every device is back or recorded lost a `RETURN_DUE`, "
       "`OVERDUE` or `DEFAULTED` contract moves to `RETURNED`; an early return during `ACTIVE` (day plan) or "
       "`ENDING` waits for the end-of-plan job (D-035). A partial check-in is allowed (MSG07).",
       "UC-43, FR-DEV-01, FR-MON-08, FR-BILL-03, E05-1, MSG07, MSG12",
       path=[C_PATH], body=[["assetTags", "Scanned tags", "string[]", "yes", "`[\"TL-0042\"]`"]],
       sample={"assetTags": ["TL-0042", "TL-0043"]},
       response={"checkedIn": ["TL-0042", "TL-0043"], "returned": 10, "total": 10, "contractStatus": "RETURNED",
                 "lateFeeVnd": 0},
       message="Check-in complete. 10 of 10 devices returned.", entity="Contract",
       errors=[(409, "DEVICE_NOT_ON_CONTRACT", "A tag is not on this contract", "TL-0099 does not belong to contract RC-2026-0042."),
               state_409("contract", "APPROVED")],
       steps=["Require ENDING, RETURN_DUE, OVERDUE or DEFAULTED, or ACTIVE for a day plan returned early",
              "Mark rows checked in",
              "Move devices to RETURNED", "Charge late days per device", "Move a RETURN_DUE, OVERDUE or DEFAULTED contract to RETURNED when complete",
              "Emit device.checkedIn per device"],
       controller="ContractsController", service="ReturnService", call="checkIn(id, dto, actor)",
       participants=[["Dev", "DevicesService"], ["Bill", "BillingService"]],
       seq=["Svc->>DB: BEGIN, SELECT contract_devices FOR UPDATE", "Svc->>Dev: markReturned(ids, tx)",
            "Svc->>Bill: chargeLate(contract, devices, tx)", "Svc->>DB: UPDATE contract if complete, COMMIT"]),

    ep("POST", "/api/contracts/:id/devices/:deviceId/lost", "Record a lost device", "TrekLink Staff",
       "Records a device lost when the organization reports it on a `RETURN_DUE`, `OVERDUE` or `DEFAULTED` "
       "contract, or when it is unrecovered after default: the device moves to `LOST` (D-035 as amended by "
       "D-038) and billing charges its remaining value from the variant's schedule (FR-BILL-05, E05-3). "
       "Counts as returned for closing the contract.",
       "UC-49, FR-DEV-01, FR-BILL-05, BR-25, E05-3, D-038",
       path=[C_PATH, D_PATH], body=[["note", "Circumstances reported by the organization", "string", "yes", "`Fell into a ravine`"]],
       sample={"note": "Reported lost in a river crossing on 2026-11-02."},
       response={"deviceId": DEVICE_ID, "assetTag": "TL-0042", "lostAt": NOW, "lossChargeVnd": 1800000},
       message="Device recorded lost", entity="Contract", errors=[NOT_ON, state_409("contract", "APPROVED")],
       steps=["Require RETURN_DUE, OVERDUE or DEFAULTED and the device not checked in", "Set lostAt", "Move the device to LOST",
              "Charge the remaining value", "Move the contract to RETURNED when complete"],
       controller="ContractsController", service="ReturnService", call="recordLost(id, deviceId, dto, actor)",
       participants=[["Dev", "DevicesService"], ["Bill", "BillingService"]],
       seq=["Svc->>Dev: markLost(deviceId, tx)", "Svc->>Bill: chargeLoss(contract, device, tx)"]),

    ep("POST", "/api/contracts/:id/devices/:deviceId/inspection", "Inspect a returned device", "TrekLink Staff",
       "Inspects a checked-in, reset device of this contract. `PASSED` moves it to `AVAILABLE`; `DAMAGED` "
       "lists damage codes, moves it to `MAINTENANCE` and has billing price each code, held for approval above "
       "the threshold (FR-BILL-04); `FAILED` moves it to `MAINTENANCE`. A device is never `AVAILABLE` without a "
       "logged reset after its last check-in (BR-28). A recovered `LOST` device is inspected through its last "
       "contract the same way; no damage is billed once that contract is `CLOSED`.",
       "UC-44, UC-47, FR-DEV-01, FR-DEV-07, FR-BILL-04, BR-04, BR-24, BR-28",
       path=[C_PATH, D_PATH],
       body=[["result", "`PASSED`, `DAMAGED` or `FAILED`", "enum", "yes", "`DAMAGED`"],
             ["damageCodes", "DamageRate codes; required for DAMAGED", "string[]", "cond.", "`[\"ANTENNA_BROKEN\"]`"],
             ["note", "Free text", "string", "no", "`Antenna snapped at the base`"]],
       sample={"result": "DAMAGED", "damageCodes": ["ANTENNA_BROKEN"], "note": "Antenna snapped at the base"},
       response={"inspection": {"id": "in-1", "result": "DAMAGED", "damageCodes": ["ANTENNA_BROKEN"], "createdAt": NOW},
                 "device": {"id": DEVICE_ID, "assetTag": "TL-0042", "status": "MAINTENANCE"},
                 "damageCharge": {"id": "dc-1", "amountVnd": 300000, "status": "APPROVED"}},
       status=201, message="Inspection recorded", entity="Contract",
       errors=[NOT_ON, (409, "RESET_REQUIRED", "No reset is logged since the last check-in",
                        "Reset this device before inspecting it."),
               (400, "UNKNOWN_DAMAGE_CODE", "A damage code is not in the schedule", "Unknown damage code: X."),
               state_409("device", "RENTED")],
       steps=["Require the device checked in on this contract and RETURNED", "DevicesService.recordInspection(tx)",
              "BillingService.chargeDamage(tx) for DAMAGED unless the contract is CLOSED"],
       controller="ContractsController", service="ReturnService", call="inspect(id, deviceId, dto, actor)",
       participants=[["Dev", "DevicesService"], ["Bill", "BillingService"]],
       seq=["Svc->>DB: BEGIN, SELECT contract_devices", "Svc->>Dev: recordInspection(deviceId, dto, actor, tx)",
            "Svc->>Bill: chargeDamage(contract, inspection, tx)", "Svc->>DB: COMMIT"]),

    ep("POST", "/api/contracts/:id/close", "Close a contract", "TrekLink Staff, TrekLink Admin",
       "Closes a `RETURNED` contract when every device is `RETURNED` or `LOST`, nothing is owed, no damage "
       "charge awaits approval, and no incident on its devices is outside `CLOSED`. Holder labels are erased "
       "(FR-CON-13, FR-CON-14, BR-27, E05-7).",
       "UC-51, FR-CON-13, FR-CON-14, BR-27, BR-33, E05-4, E05-7, MSG29",
       path=[C_PATH], body=[VERSION], sample={"expectedVersion": 9},
       response={**CONTRACT, "status": "CLOSED", "closedAt": NOW}, message="Contract closed", entity="Contract",
       errors=[(409, "BALANCE_OUTSTANDING", "An invoice line is unpaid or a damage charge is pending",
                "This cannot be done while it has open balances."),
               (409, "OPEN_INCIDENTS", "An incident on one of its devices is not CLOSED",
                "This cannot be done while it has open incidents."),
               state_409("contract", "OVERDUE"), STALE],
       steps=["Require RETURNED", "Ask billing for the balance", "Ask incidents for open incidents",
              "Erase holder labels", "Move to CLOSED"],
       controller="ContractsController", service="ContractLifecycleService", call="close(id, dto, actor)",
       participants=[["Bill", "BillingService"], ["Inc", "IncidentsService"]],
       seq=["Svc->>Bill: outstanding(contractId)", "Svc->>Inc: openIncidentCount(deviceIds)",
            "Svc->>DB: UPDATE contract_devices SET holder* = NULL; UPDATE contract; INSERT transition"]),

    ep("GET", "/api/contracts/:id/transitions", "Contract state history",
       "Org Manager: own; TrekLink Staff, TrekLink Admin",
       "Returns the append-only state history with actor (or SYSTEM for scheduler moves) and reason.",
       "UC-55, D-035", path=[C_PATH],
       response=[{"fromStatus": "APPROVED", "toStatus": "ACTIVE", "actor": "Tran Thi B", "reason": "HANDED_OVER",
                  "createdAt": NOW}],
       entity="Contract", steps=["Read contract_transitions"], controller="ContractsController",
       service="ContractsService", call="transitions(id, caller)", seq=["Svc->>DB: SELECT contract_transitions"]),
]

NOTES = ("Scheduler moves that have no endpoint (rentals design §5): term rollover and day-plan end "
         "(UC-24, FR-CON-08, FR-CON-10), `RETURN_DUE` to `OVERDUE` to `DEFAULTED` (UC-50, FR-CON-12), and the "
         "reservation-expiry reminder (FR-CON-04).")
