#!/usr/bin/env python3
"""Generate the seed migration and the two catalog pages from scripts/specs/catalog.py.

    python3 scripts/specs/build_seed.py

Writes:
  backend/prisma/migrations/20261004120100_seed/migration.sql   parameters, roles, permissions, grants
  specs/platform/configuration-matrix.md                        every business parameter (NFR-CFG-02)
  specs/auth/permission-matrix.md                               every permission by role (FR-AUTH-06)
Edit catalog.py, never the outputs. While the baseline is not applied to a shared database (D-036)
the seed migration is rewritten in place; after that, a change becomes a new forward migration.
"""
import json
from pathlib import Path

from catalog import INHERITS, PARAMETERS, PERMISSIONS, ROLES

ROOT = Path(__file__).resolve().parents[2]
SEED = ROOT / "backend/prisma/migrations/20261004120100_seed/migration.sql"


def q(v):
    return "NULL" if v is None else "'" + str(v).replace("'", "''") + "'"


def grants():
    """(role, permission key) with FR-AUTH-10 inheritance applied."""
    out = set()
    for key, _, _, _, roles in PERMISSIONS:
        for r in roles:
            out.add((r, key))
    for parent, child in INHERITS.items():
        out |= {(parent, k) for (r, k) in list(out) if r == child}
    return sorted(out)


def seed_sql():
    rows = []
    for module, params in PARAMETERS.items():
        for key, default, typ, bounds, unit, desc, _ in params:
            rows.append(f"  ({q(key)}, {q(json.dumps(default, ensure_ascii=False))}::jsonb, {q(typ)}, "
                        f"{'NULL' if bounds is None else q(json.dumps(bounds)) + '::jsonb'}, {q(unit)}, {q(module)}, "
                        f"{q(desc)}, 1, CURRENT_TIMESTAMP)")
    g = grants()
    out = ["-- Seed generated by scripts/specs/build_seed.py from scripts/specs/catalog.py. Do not edit.",
           f"-- {len(rows)} parameters, {len(ROLES)} roles, {len(PERMISSIONS)} permissions, {len(g)} grants.", "",
           'INSERT INTO "business_parameters" ("key", "value", "valueType", "bounds", "unit", "ownerModule", '
           '"description", "version", "updatedAt") VALUES', ",\n".join(rows) + ";", "",
           'INSERT INTO "roles" ("id", "key", "name", "accountType", "isSystem") VALUES',
           ",\n".join(f"  (gen_random_uuid()::text, {q(k)}, {q(n)}, {q(t)}, true)" for k, n, t in ROLES) + ";", "",
           'INSERT INTO "permissions" ("id", "key", "action", "subject", "conditions", "fields") VALUES',
           ",\n".join(f"  (gen_random_uuid()::text, {q(k)}, {q(a)}, {q(s)}, "
                      f"{'NULL' if c is None else q(json.dumps(c)) + '::jsonb'}, ARRAY[]::text[])"
                      for k, a, s, c, _ in PERMISSIONS) + ";", "",
           'INSERT INTO "role_permissions" ("roleId", "permissionId")',
           'SELECT r."id", p."id" FROM (VALUES',
           ",\n".join(f"  ({q(r)}, {q(k)})" for r, k in g),
           ') AS g("role", "perm")',
           'JOIN "roles" r ON r."key" = g."role"',
           'JOIN "permissions" p ON p."key" = g."perm";', ""]
    return "\n".join(out)


def matrix_md():
    out = ["# Configuration Matrix", "",
           "> Generated by `scripts/specs/build_seed.py` from `scripts/specs/catalog.py`; edit the catalog. Every "
           "business parameter of the platform (D-015, NFR-CFG-01, NFR-CFG-02). Location: the "
           "`business_parameters` table, editable live by a TrekLink Admin (`PATCH /api/parameters/:key`); "
           "demonstration path for each row: change it there, then repeat the action that reads it (BR-29). "
           "Environment variables are listed in `specs/platform/requirements.md` §4.", ""]
    for module, params in PARAMETERS.items():
        out += [f"## {module}", "", "| Key | Default | Type | Bounds | Unit | Meaning | Requirement |",
                "|---|---|---|---|---|---|---|"]
        for key, default, typ, bounds, unit, desc, req in params:
            b = "" if bounds is None else f"{bounds['min']} to {bounds['max']}"
            out.append(f"| `{key}` | `{json.dumps(default, ensure_ascii=False)}` | {typ} | {b} | {unit or ''} | {desc} | {req} |")
        out.append("")
    return "\n".join(out)


def permissions_md():
    g = set(grants())
    keys = [r[0] for r in ROLES]
    out = ["# Permission Matrix", "",
           "> Generated by `scripts/specs/build_seed.py` from `scripts/specs/catalog.py`; edit the catalog. Roles "
           "and permissions are data (FR-AUTH-06), seeded by the seed migration. `own` conditions bind to the "
           "caller's organization from the token (FR-AUTH-11). An Admin holds every Staff permission and an Org "
           "Manager every Org Operator permission (FR-AUTH-10). Screen-level rights: SRS Table 72.", "",
           "| Permission | Action | Subject | Condition | " + " | ".join(keys) + " |",
           "|---|---|---|---|" + "---|" * len(keys)]
    for k, a, s, c, _ in PERMISSIONS:
        cond = "" if c is None else "`" + json.dumps(c) + "`"
        out.append(f"| `{k}` | {a} | {s} | {cond} | " + " | ".join("X" if (r, k) in g else "" for r in keys) + " |")
    return "\n".join(out) + "\n"


def main():
    SEED.parent.mkdir(parents=True, exist_ok=True)
    SEED.write_text(seed_sql())
    (ROOT / "specs/platform").mkdir(parents=True, exist_ok=True)
    (ROOT / "specs/auth").mkdir(parents=True, exist_ok=True)
    (ROOT / "specs/platform/configuration-matrix.md").write_text(matrix_md())
    (ROOT / "specs/auth/permission-matrix.md").write_text(permissions_md())
    print(f"seed: {sum(len(v) for v in PARAMETERS.values())} parameters, {len(PERMISSIONS)} permissions, {len(grants())} grants")


if __name__ == "__main__":
    main()
